name: Pull Request Merged

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been merged

        curl --location --request POST 'https://enn078zfxb8q7wa.m.pipedream.net/github' \
        --header 'Content-Type: application/json' \
        --data-raw ${{ github.event }}